config/routes.rb
Rails.application.routes.draw do
  #about page
  get "about", to: "about#index"
  get "home" , to: "home#index",via: 'get'
  get "/" , to:"home#index",via: 'get'
  get "register" , to:"register#index"
  post "register" , to:"register#new"
  get 'student', to: "home#show"
  delete 'student', to: "home#deleteall"

  get 'edit' , to: "edit#index"
  patch 'edit', to: "edit#update"
  get 'delete', to: "delete#index"
  delete 'delete', to: "delete#delete"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
    has_secure_password

    validates :email, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/delete_controller.rb
class DeleteController < ApplicationController
    def index
        id = params['id'];
        @student = Student.find(id)
    end
    def delete
        id = params['id'];
        @student = Student.find(id)
        if @student.delete
            redirect_to home_path, notice: "Delete successfully"

        else
            render :index
        end
    end
end

app/controllers/edit_controller.rb
class EditController < ApplicationController
        def index
            id = params['id'];
            @student = Student.find(id)
        end
        
     def update
            id = params.require(:student).permit(:id)
            @student = Student.find(id['id'])
            if @student.update(student_parms)
                redirect_to home_path, notice: "Update successfully"
    
            else
                render :index
            end
    
        end
        private
        def student_parms
            params.require(:student).permit(:email, :password , :name , :address , :phone)
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @students = Student.new
    end
    def show
        @student = Student.find(params['id'])
    end
    def deleteall
        @students = Student.all
        if @students.delete_all
            redirect_to home_path
        else
            render :index
        end
    end

end

app/controllers/register_controller.rb
class RegisterController  < ApplicationController
    def index
       @student = Student.new
    end
    
    def show
        @students = Stuent.new
    end

    def new
        @student = Student.new(student_parms)
        if @student.save
            redirect_to home_path, notice: "Sign up successfully"

        else
            render :index
        end

    end
    private
    def student_parms
        params.require(:student).permit(:email, :password , :name , :address , :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/component/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to"Home", home_path , class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to"Register", register_path , class:"nav-link" %>
        </li>
        <li class="nav-item">
         <%= link_to"About", about_path , class:"nav-link" %>
         </li>
      </ul>
    </div>
  </div>
</nav>

app/views/delete/index.html.erb
<h1>Are you sure to delete?</h1>
<table class="table table-bordered table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Address</th>
    </tr>
  </thead>
  <tbody>
  <tr>
      <th scope="row"><%= @student.id %></th>
      <td> <%= @student.name %></td>
      <td> <%= @student.email %></td>
      <td> <%= @student.address %></td>
      <td> <%= @student.phone %></td>
    </tr>
    </tbody>
</table>
<div align="center">
<%= link_to "Delete", delete_path(:id => @student.id) , method: :delete, :class => "btn" %>
</div>

app/views/edit/index.html.erb
<h1>Edit Student</h1>
<%= form_with model: @student, url: edit_path do |form| %>
<% if @student.errors.any?  %>
 <div class = "alert alert-danger">
   <% @student.errors.full_messages.each do|messages|  %>
     <div> <%= messages %> </div>
   <% end %>
 </div>
<% end %>
<div class = "mb-3">
  <%= form.label :id %>
  <%= form.text_field :id , class:"form-control" ,placeholder: "Id", :readonly => true%>
</div>
<div class = "mb-3">
  <%= form.label :name %>
  <%= form.text_field :name , class:"form-control" ,placeholder: "Name" %>
</div>
<div class = "mb-3">
  <%= form.label :email %>
  <%= form.text_field :email , class:"form-control" ,placeholder: "Email" %>
</div>
<div class = "mb-3">
  <%= form.label :password %>
  <%= form.password_field :password ,class:"form-control", placeholder: "NewPassword" %>
</div>
<div class = "mb-3">
  <%= form.label :address %>
  <%= form.text_field :address,class:"form-control", placeholder: "Address" %>
</div>
<div class = "mb-3">
  <%= form.label :phone %>
  <%= form.text_field :phone,class:"form-control", placeholder: "Phone" %>
</div>
<div class = "mb-3">
  <%= form.submit %>
</div>
<% end %>

app/views/home/deleteall.html.erb
<h1 align="center">Are you sure to delete all students?</h1>
<% button_to="Delete All", student_path , method: :delete%>

app/views/home/index.html.erb
<h1 align="center">This is Our Student Page</h1>
Total Student <%= Student.all.length() %>
<br/>
<table class="table table-bordered table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Address</th>
    </tr>
  </thead>
  <tbody>
  <% id = 1%>
<% Student.all.each do |user| %>
      <tr>
      <th scope="row"><%= id %></th>
      <td> <%= user.name %></td>
      <td> <%= user.email %></td>
      <td> <%= user.address %></td>
      <td> <%= user.phone %></td>
      <td> <%= link_to"View", student_path(:id => user.id) , class:"nav-link" %> </td>
      <td> <%= link_to"Edit", edit_path(:id => user.id) , class:"nav-link" %> </td>
      <td> <%= link_to"Delete", delete_path(:id => user.id) , class:"nav-link" %> </td>
    </tr>
    <% id += 1 %>
<% end %>
</tbody>
</table>
<div align="center">
<%= button_to"Delete All", student_path,method: :delete ,class:"btn btn-dark" %>
</div>

app/views/home/show.html.erb
<h1>Student Detail Page</h1>
<table class="table table-bordered table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Address</th>
    </tr>
  </thead>
  <tbody>
  <tr>
      <th scope="row"><%= @student.id %></th>
      <td> <%= @student.name %></td>
      <td> <%= @student.email %></td>
      <td> <%= @student.address %></td>
      <td> <%= @student.phone %></td>
    </tr>
    </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Students</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "component/nav"  %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/register/index.html.erb
<h1>Sign Up</h1>
<%= form_with model: @student, url: register_path do |form| %>
<% if @student.errors.any?  %>
 <div class = "alert alert-danger">
   <% @student.errors.full_messages.each do|messages|  %>
     <div> <%= messages %> </div>
   <% end %>
 </div>
<% end %>
<div class = "mb-3">
  <%= form.label :email %>
  <%= form.text_field :email , class:"form-control" ,placeholder: "Email" %>
</div>
<div class = "mb-3">
  <%= form.label :password %>
  <%= form.password_field :password ,class:"form-control", placeholder: "Password" %>
</div>
<div class = "mb-3">
  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation,class:"form-control", placeholder: "Confirm Password" %>
</div>
<div class = "mb-3">
  <%= form.submit %>
</div>
<% end %>